a = set([1,2,3,4])
print(a)
b = set([3,4,5,6])
print(b)
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))
print(a ^ b)
print(a | b)
print(a & b) #symmetricdifference
c = a.copy()
print(c)
d = set([3,4])
print(d.issubset(a))
print(a.issuperset(d))