a = set([1,2,3,4])
print(a)
b = set([3,4,5,6])
print(b)
print(a.union(b))
print(a.intersection(b))
print("a difference b")
print(a.difference(b))
print(b.difference(a))
print(a ^ b)
print(a | b)
print(a & b) #symmetricdifference
c = a.copy()
print(c)
d = set([3,4])
print(d.issubset(a))
print(a.issuperset(d))
b = {1,2,3,4}
print(b)
numberTuple = range(0,40,5)
c = set(numberTuple)
a.add(5)
print(c)
print(a)
print(b)
a.difference_update(c)
print("a difup c")
print(a)
a.add(5)
a.remove(5)
a.discard(4)
a.remove(5) #error
a.discard(4)



